name: Deploy to Surge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Surge
      run: npm install --global surge

    - name: Build and Deploy
      env:
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge --project ./ --domain webpage.surge.sh
